FROM python:3.10.14-slim-bullseye

WORKDIR /home/sq

COPY simd.patch simd.patch

RUN apt update && apt install -y --no-install-recommends git build-essential cmake && rm -rf /var/lib/apt/lists/* \
    && git clone https://github.com/ScQ-Cloud/pyquafu.git && cd pyquafu && git checkout v0.4.1 && git apply ../simd.patch \
    && pip install --no-cache-dir -r requirements.txt && python setup.py install && cd .. && rm -rf pyquafu

RUN python3 -m pip install --no-cache-dir httpx loguru numpy==1.26.4

WORKDIR /home/sq/quafu-agent-py
COPY . .

ENV QUAFU_IP=120.46.209.71
ENV SYSTEM_ID=7

ENTRYPOINT [ "python3", "quafu-agent.py" ]